import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import playersRouter from "./players";
import teamsRouter from "./teams";
import matchesRouter from "./matches";
import awardsRouter from "./awards";
import leaderboardRouter from "./leaderboard";
import uploadRouter from "./upload";
import leaguesRouter from "./leagues";
import trophiesRouter from "./trophies";
import ffpRouter from "./ffp";
import ballonDorRouter from "./ballondor";
import exportRouter from "./export";
import ceremonyRouter from "./ceremony";
import migrateRouter from "./migrate";
import transfersRouter from "./transfers";
import aiRouter from "./ai";
import cmsRouter from "./cms";
import incidentsRouter from "./incidents";
import gccRouter from "./gcc";
import budgetRouter from "./budget";
import taglistRouter from "./taglist";
import teamRecordsRouter from "./teamrecords";
import efcardsRouter from "./efcards";
import efworldRouter from "./efworld";
import contractsRouter from "./contracts";
import predictionsRouter from "./predictions";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(playersRouter);
router.use(teamsRouter);
router.use(matchesRouter);
router.use(awardsRouter);
router.use(leaderboardRouter);
router.use(uploadRouter);
router.use(leaguesRouter);
router.use(trophiesRouter);
router.use(ffpRouter);
router.use(ballonDorRouter);
router.use(exportRouter);
router.use(ceremonyRouter);
router.use(migrateRouter);
router.use(transfersRouter);
router.use(aiRouter);
router.use(cmsRouter);
router.use(incidentsRouter);
router.use(gccRouter);
router.use(budgetRouter);
router.use(taglistRouter);
router.use(teamRecordsRouter);
router.use(efcardsRouter);
router.use(efworldRouter);
router.use(contractsRouter);
router.use(predictionsRouter);

export default router;
